#!/bin/bash
#
# Gather up the QuickUI tools (binaries, scripts, etc.) for OS/X and Linux
# under mono.
#
# Relies on the ZIP utility 7-Zip from 7-zip.org.

# Get location of parent QuickUI folder relative to location of this script.
scriptPath=$(cd ${0%/*} && echo $PWD/${0##*/})
scriptFolder=`dirname "$scriptPath"`
quickui="$scriptFolder/.."
mono="$quickui/mono"

# The line endings of the mono bin scripts should be Unix style, but can end
# with Windows (crlf) style line endings. Force deletion of carriage returns.
bin="$mono/bin"
cp $bin/qb $quickui/qb.orig
cp $bin/qc $quickui/qc.orig
tr -d '\r' < $quickui/qb.orig > $bin/qb
tr -d '\r' < $quickui/qc.orig > $bin/qc

# Clear mono lib folder.
lib="$mono/lib"
if [ -d $lib ]; then
    # Remove write protection on lib files like quicommon.*
    # chmod +w $lib/*
    rm -r $lib
fi
mkdir $lib

# Copy tool outputs to mono lib folder.
cp $quickui/tools/qb/bin/Release/qb.exe $lib
cp $quickui/tools/qb/bin/Release/qc.exe $lib

# Build ZIP file for OS/X.
zipFile="$scriptFolder/QuickUI.zip"
if [ -f $zipFile ]; then
    rm $zipFile
fi
7z a $zipFile $mono/* -r > /dev/null

# Restore the original bin files
mv $quickui/qb.orig $bin/qb
mv $quickui/qc.orig $bin/qc
